users:
    path: /users
    controller: App\Controller\UserController::index
    methods: [GET]

rooms:
    path: /rooms
    controller: App\Controller\RoomController::index
    methods: [GET]

group-instances:
    path: /group-instances
    controller: App\Controller\GroupInstanceController::index
    methods: [GET]

groups:
    path: /groups
    controller: App\Controller\GroupController::index
    methods: [GET]

devices:
    path: /devices
    controller: App\Controller\DeviceController::index
    methods: [GET]

button-templates:
    path: /button-templates
    controller: App\Controller\ButtonTemplateController::index
    methods: [GET]

button-instances:
    path: /button-instances
    controller: App\Controller\ButtonInstanceController::index
    methods: [GET]

belongs:
    path: /belongs
    controller: App\Controller\BelongsController::index
    methods: [GET]
