all-users:
    path: api/users
    controller: App\Controller\UserController::findAllUsers
    methods: [GET]

one-user:
    path: api/user/{id}
    controller: App\Controller\UserController::findUserById
    requirements:
        id: !php/const Symfony\Component\Routing\Requirement\Requirement::DIGITS
    methods: [GET]

user-button-instances:
    path: api/user/{userName}/button-instances
    controller: App\Controller\UserController::findButtonInstancesByUserName
    methods: [GET]

create-user-button-instance:
    path: /api/user/{userName}/button-instances/save
    controller: App\Controller\ButtonInstanceController::saveButtonInstance
    methods: [POST]

user-redux-span:
    path: api/user/{userName}/redux-span
    controller: App\Controller\UserController::findReduxSpanByUserName
    methods: [GET]

create-user-redux-span:
    path: api/user/{userName}/redux-span/save
    controller: App\Controller\UserController::addReduxSpan
    methods: [POST]

all-rooms:
    path: api/rooms
    controller: App\Controller\RoomController::findAllRooms
    methods: [GET]

one-room:
    path: api/room/{id}
    controller: App\Controller\RoomController::findRoomById
    requirements:
        id: !php/const Symfony\Component\Routing\Requirement\Requirement::DIGITS
    methods: [GET]

room-devices:
    path: api/room/{id}/devices
    controller: App\Controller\RoomController::getDevicesByRoom
    requirements:
        id: !php/const Symfony\Component\Routing\Requirement\Requirement::DIGITS
    methods: [GET]

all-group-instances:
    path: api/group-instances
    controller: App\Controller\GroupInstanceController::findAllGroupInstances
    methods: [GET]

one-group-instance:
    path: api/group-instance/{id}
    controller: App\Controller\GroupInstanceController::findGroupInstanceById
    requirements:
        id: !php/const Symfony\Component\Routing\Requirement\Requirement::DIGITS
    methods: [GET]

all-groups:
    path: api/button-groups
    controller: App\Controller\ButtonGroupController::findAllButtonGroups
    methods: [GET]

one-group:
    path: api/button-group/{id}
    controller: App\Controller\ButtonGroupController::findButtonGroupById
    requirements:
        id: !php/const Symfony\Component\Routing\Requirement\Requirement::DIGITS
    methods: [GET]

all-devices:
    path: api/devices
    controller: App\Controller\DeviceController::findAllDevices
    methods: [GET]

one-device:
    path: api/device/{id}
    controller: App\Controller\DeviceController::findDeviceById
    requirements:
        id: !php/const Symfony\Component\Routing\Requirement\Requirement::DIGITS
    methods: [GET]

all-button-templates:
    path: api/button-templates
    controller: App\Controller\ButtonTemplateController::findAllButtonTemplates
    methods: [GET]

one-button-template:
    path: api/button-template/{id}
    controller: App\Controller\ButtonTemplateController::findButtonTemplateById
    requirements:
        id: !php/const Symfony\Component\Routing\Requirement\Requirement::DIGITS
    methods: [GET]

create-button-template:
    path: api/button-template/save
    controller: App\Controller\ButtonTemplateController::createButtonTemplate
    methods: [POST]

all-button-instances:
    path: api/button-instances
    controller: App\Controller\ButtonInstanceController::findAllButtonInstances
    methods: [GET]

one-button-instance:
    path: api/button-instance/{id}
    controller: App\Controller\ButtonInstanceController::findButtonInstanceById
    requirements:
        id: !php/const Symfony\Component\Routing\Requirement\Requirement::DIGITS
    methods: [GET]

all-belongs:
    path: api/belongs
    controller: App\Controller\BelongsController::findAllBelongs
    methods: [GET]

one-belongs:
    path: api/belongs/{id}
    controller: App\Controller\BelongsController::findBelongsById
    methods: [GET]

register:
    path: api/register
    controller: App\Controller\AuthenticationController::register
    methods: [POST]

login:
    path: api/login
    controller: App\Controller\AuthenticationController::login
    methods: [POST]

logout:
    path: api/logout
    controller: App\Controller\AuthenticationController::logout
    methods: [POST]

update-password:
    path: api/update-password
    controller: App\Controller\AuthenticationController::updatePassword
    methods: [POST]

verify:
    path: api/verify
    controller: App\Controller\AuthenticationController::verify
    methods: [POST]

lights-test:
    path: api/test/lights
    controller: App\Controller\TestController::testPositiveOutput
    methods: [POST]
