users:
    path: api/users
    controller: App\Controller\UserController::findAllUsers
    methods: [GET]

rooms:
    path: api/rooms
    controller: App\Controller\RoomController::findAllRooms
    methods: [GET]

group-instances:
    path: api/group-instances
    controller: App\Controller\GroupInstanceController::findAllGroupInstances
    methods: [GET]

groups:
    path: api/groups
    controller: App\Controller\GroupController::findAllGroups
    methods: [GET]

devices:
    path: api/devices
    controller: App\Controller\DeviceController::findAllDevices
    methods: [GET]

button-templates:
    path: api/button-templates
    controller: App\Controller\ButtonTemplateController::findAllButtonTemplates
    methods: [GET]

button-instances:
    path: api/button-instances
    controller: App\Controller\ButtonInstanceController::findAllButtonInstances
    methods: [GET]

belongs:
    path: api/belongs
    controller: App\Controller\BelongsController::findAllBelongs
    methods: [GET]
