all-users:
    path: api/users
    controller: App\Controller\UserController::findAllUsers
    methods: [GET]

one-user:
    path: api/user/{id}
    controller: App\Controller\UserController::findUserById
    requirements:
        id: !php/const Symfony\Component\Routing\Requirement\Requirement::DIGITS
    methods: [GET]

user-button-instances:
    path: api/user/{userName}/button-instances
    controller: App\Controller\UserController::findButtonInstancesByUserName
    methods: [GET]

all-rooms:
    path: api/rooms
    controller: App\Controller\RoomController::findAllRooms
    methods: [GET]

one-room:
    path: api/room/{id}
    controller: App\Controller\RoomController::findRoomById
    requirements:
        id: !php/const Symfony\Component\Routing\Requirement\Requirement::DIGITS
    methods: [GET]

room-devices:
    path: api/room/{id}/devices
    controller: App\Controller\RoomController::getDevicesByRoom
    requirements:
        id: '\d+'
    methods: [GET]

all-group-instances:
    path: api/group-instances
    controller: App\Controller\GroupInstanceController::findAllGroupInstances
    methods: [GET]

one-group-instance:
    path: api/group-instance/{id}
    controller: App\Controller\GroupInstanceController::findGroupInstanceById
    requirements:
        id: !php/const Symfony\Component\Routing\Requirement\Requirement::DIGITS
    methods: [GET]

all-groups:
    path: api/button-groups
    controller: App\Controller\ButtonGroupController::findAllButtonGroups
    methods: [GET]

one-group:
    path: api/button-group/{id}
    controller: App\Controller\ButtonGroupController::findButtonGroupById
    requirements:
        id: !php/const Symfony\Component\Routing\Requirement\Requirement::DIGITS
    methods: [GET]

all-devices:
    path: api/devices
    controller: App\Controller\DeviceController::findAllDevices
    methods: [GET]

one-device:
    path: api/device/{id}
    controller: App\Controller\DeviceController::findDeviceById
    requirements:
        id: !php/const Symfony\Component\Routing\Requirement\Requirement::DIGITS
    methods: [GET]

all-button-templates:
    path: api/button-templates
    controller: App\Controller\ButtonTemplateController::findAllButtonTemplates
    methods: [GET]

one-button-template:
    path: api/button-template/{id}
    controller: App\Controller\ButtonTemplateController::findButtonTemplateById
    requirements:
        id: !php/const Symfony\Component\Routing\Requirement\Requirement::DIGITS
    methods: [GET]

all-button-instances:
    path: api/button-instances
    controller: App\Controller\ButtonInstanceController::findAllButtons
    methods: [GET]

one-button-instance:
    path: api/button-instance/{id}
    controller: App\Controller\ButtonInstanceController::findButtonInstanceById
    requirements:
        id: !php/const Symfony\Component\Routing\Requirement\Requirement::DIGITS
    methods: [GET]

all-belongs:
    path: api/belongs
    controller: App\Controller\BelongsController::findAllBelongs
    methods: [GET]

one-belongs:
    path: api/belongs/{id}
    controller: App\Controller\BelongsController::findBelongsById
    methods: [GET]
