nelmio_api_doc:
    documentation:
        info:
            title: Suvepraktika
            description: Suvepraktika rühm 2.
            version: 1.0.0
        paths:
            /api/users:
                get:
                    summary: "Get all users"
                    responses:
                        200:
                            description: "Returns all users without passwords"
                        404:
                            description: "No users found from database"
                        default:
                            description: "Unexpected error"
            /api/user/{id}:
                get:
                    summary: "Find user by id"
                    responses:
                        200:
                            description: "Returns one user based on id"
                        404:
                            description: "user not found from database"
                        default:
                            description: "unexpected error"
            /api/user/{userName}/button-instances:
                get:
                    summary: "find buttons for a user"
                    responses:
                        200:
                            description: "Returns all buttons, and button templates for a single user"
                        404:
                            description: "user not found from database"
                        default:
                            description: "unexpected error"
            /api/rooms:
                get:
                    summary: "Find all rooms"
                    responses:
                        200:
                            description: "Returns all rooms from the database"
                        default:
                            description: "unexpected error"
            /api/room/{id}:
                get:
                    summary: "Find one room"
                    responses:
                        200:
                            description: "Returns one room based on id"
                        default:
                            description: "unexpected error"
            /api/room/{id}/devices:
                get:
                    summary: "Find all devices in a single room"
                    responses:
                        200:
                            description: "Returns all devices in a single room, based on room id"
                        default:
                            description: "unexpected error"
            /api/group-instances:
                get:
                    summary: "Find all group-instances"
                    responses:
                        200:
                            description: "Return all group instances"
                        default:
                            description: "unexpected error"
            /api/group-instance/{id}:
                get:
                    summary: "Find one group instance"
                    responses:
                        200:
                            description: "Return one group instance based on group instance id"
                        default:
                            description: "unexpected error"
            /api/button-groups:
                get:
                    summary: "Find all button groups"
                    responses:
                        200:
                            description: "Returns all button groups"
                        default:
                            description: "unexpected error"
            /api/button-group/{id}:
                get:
                    summary: "Find a button-group by id"
                    responses:
                        200:
                            description: "Returns button-group based on button-group id"
                        default:
                            description: "unexpected error"
            /api/devices:
                get:
                    summary: "Find all devices"
                    responses:
                        200:
                            description: "Returns all devices from database"
                        default:
                            description: "unexpected error"
            /api/device/{id}:
                get:
                    summary: "Find one device by id"
                    responses:
                        200:
                            description: "Returns all devices based on device id"
                        default:
                            description: "unexpected error"
            

            
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
